<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
	<LangVersion>latestMajor</LangVersion>
	<OutputType>Library</OutputType>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	
	<GameVer>1.6</GameVer>
	<Configurations>Debug;Release Current</Configurations>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>TRACE;DEBUG</DefineConstants>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisIgnoreGeneratedCode>false</CodeAnalysisIgnoreGeneratedCode>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' != 'Debug' ">
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release Current' ">
    <DefineConstants>TRACE;RELEASE_CURRENT</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>..\..\$(GameVer)\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref">
	  <Version>$(GameVer).*-*</Version>
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

</Project>
